subplot(1,2,1)

errorbar((1:num_prof_points)*dR, nanmean([accum_vel_prof_e1_CDH2;...
accum_vel_prof_e2_CDH2]), nanstd([accum_vel_prof_e1_CDH2;...
accum_vel_prof_e2_CDH2]))

subplot(1,2,2)

errorbar((1:num_prof_points)*dR, nanmean([accum_vort_prof_e1_CDH2;...
accum_vort_prof_e2_CDH2]), nanstd([accum_vort_prof_e1_CDH2;...
accum_vort_prof_e2_CDH2]))